import { GoogleGenAI, Type } from "@google/genai";
import { Question } from "../types";

let aiClient: GoogleGenAI | null = null;

function getAIClient() {
  if (!aiClient) {
    const key = process.env.GEMINI_API_KEY;
    if (!key) throw new Error("GEMINI_API_KEY is not set.");
    aiClient = new GoogleGenAI({ apiKey: key });
  }
  return aiClient;
}

export async function parseQuestions(questionsText: string, answerKeyText: string = ""): Promise<Question[]> {
  const ai = getAIClient();
  const response = await ai.models.generateContent({
    model: "gemini-3.1-pro-preview",
    contents: `Parse the following questions text, and match them with the provided answer key text (if any).
    
Create a structured JSON output representing the multiple-choice questions. 
For each question:
- Extract the question text.
- Extract all the options as an array of strings.
- Identify the index of the correct answer (0-based) in the options array. If an answer key is provided, follow it strictly. If not, deduce the correct answer.
- Provide a clear, brief explanation for why the answer is correct.

Questions Text:
${questionsText}

Answer Key Text:
${answerKeyText || "None provided."}`,
    config: {
      responseMimeType: "application/json",
      responseSchema: {
        type: Type.ARRAY,
        items: {
          type: Type.OBJECT,
          properties: {
            text: { type: Type.STRING, description: "The text of the question." },
            options: { type: Type.ARRAY, items: { type: Type.STRING }, description: "Array of possible options." },
            correctAnswerIndex: { type: Type.INTEGER, description: "The 0-based index of the correct option in the options array." },
            explanation: { type: Type.STRING, description: "A detailed explanation of why the answer is correct." }
          },
          required: ["text", "options", "correctAnswerIndex", "explanation"]
        }
      }
    }
  });

  const textOutput = response.text;
  if (!textOutput) {
    throw new Error("No output generated by AI.");
  }

  try {
    const parsed = JSON.parse(textOutput);
    return parsed.map((item: any, index: number) => ({
      id: `q-${index}-${Date.now()}`,
      text: item.text,
      options: item.options,
      correctAnswerIndex: item.correctAnswerIndex,
      explanation: item.explanation
    }));
  } catch (e) {
     console.error("Failed to parse JSON:", textOutput);
     throw new Error("Failed to parse AI output into valid questions format.");
  }
}
